### ISSUE TITLE
To do: Create fragments to reuse

### ISSUE THREAD

**Issue by steina1989** [steina1989/Soguheimur#2]
We should start thinking about creating index pages with thymeleaf fragments and look more into the front end.

**Comment by hrafnhilduroh** [comment]
After designing a header for the site we decided to use the fragments for the header and links at the bottom of the site so the code looks cleaner and is easier to go over. After creating a header html file I linked it to our test page of login using thymeleaf fragments and it was successful. Now it's possible to link the header to the remaining pages that we will have along with the navigation bar for the bottom of the page with links to other parts of the website.
